# Generated by Django 6.1.1 on 2026-09-10 15:49

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m5ka_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomisationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastfm_username', models.CharField(blank=True, max_length=128, verbose_name='LastFM username')),
                ('github_username', models.CharField(blank=True, max_length=128)),
                ('linkedin_username', models.CharField(blank=True, max_length=128, verbose_name='LinkedIn username')),
                ('short_bio', models.TextField(blank=True, help_text='A short bio to appear on the homepage')),
                ('footer_text', wagtail.fields.RichTextField(blank=True)),
                ('copyright_author', models.CharField(blank=True, max_length=64)),
                ('goatcounter_hostname', models.CharField(blank=True, help_text='If you are tracking metrics via GoatCounter, this should be just the hostname section of the URL - e.g. goatcounter.example.com', max_length=64, verbose_name='GoatCounter hostname')),
            ],
            options={
                'verbose_name': 'Customisation',
            },
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_links', wagtail.fields.StreamField([('page', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'icon': 'doc-empty'})})),
                ('hamburger_links', wagtail.fields.StreamField([('page', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'icon': 'doc-empty'})})),
                ('footer_links', wagtail.fields.StreamField([('page', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'icon': 'doc-empty'})})),
            ],
            options={
                'verbose_name': 'Navigation',
            },
        ),
    ]
