# Generated by Django 6.1.1 on 2026-09-12 12:11

import django.db.models.deletion
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m5ka_core', '0001_initial'),
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('standout_text', 3), ('image', 7), ('page_link', 8), ('page_cards', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'h2', 'template': 'blocks/subheading.html'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'hr', 'link']}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'template': 'blocks/standout_text.html'}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('thumb', 'Thumbnail'), ('full', 'Full')]}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('size', 6)]], {}), 8: ('wagtail.blocks.PageChooserBlock', (), {'icon': 'link', 'template': 'blocks/page_link.html'}), 9: ('wagtail.blocks.PageChooserBlock', (), {}), 10: ('wagtail.blocks.ListBlock', (9,), {'icon': 'table', 'template': 'blocks/page_cards.html'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogRoot',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_links', wagtail.fields.StreamField([('page', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'icon': 'doc-empty'})})),
                ('hamburger_links', wagtail.fields.StreamField([('page', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'icon': 'doc-empty'})})),
                ('footer_links', wagtail.fields.StreamField([('page', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'icon': 'doc-empty'})})),
            ],
            options={
                'verbose_name': 'Navigation',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('standout_text', 3), ('image', 7), ('page_link', 8), ('page_cards', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'h2', 'template': 'blocks/subheading.html'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'hr', 'link']}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'template': 'blocks/standout_text.html'}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('thumb', 'Thumbnail'), ('full', 'Full')]}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('size', 6)]], {}), 8: ('wagtail.blocks.PageChooserBlock', (), {'icon': 'link', 'template': 'blocks/page_link.html'}), 9: ('wagtail.blocks.PageChooserBlock', (), {}), 10: ('wagtail.blocks.ListBlock', (9,), {'icon': 'table', 'template': 'blocks/page_cards.html'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SocialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastfm_username', models.CharField(blank=True, max_length=128, verbose_name='LastFM username')),
                ('github_username', models.CharField(blank=True, max_length=128)),
                ('linkedin_username', models.CharField(blank=True, max_length=128, verbose_name='LinkedIn username')),
                ('goatcounter_hostname', models.CharField(blank=True, help_text='If you are tracking metrics via GoatCounter, this should be just the hostname section of the URL - e.g. goatcounter.example.com', max_length=64, verbose_name='GoatCounter hostname')),
                ('homepage_avatar', models.ForeignKey(blank=True, help_text='An avatar image to appear on the homepage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Social',
            },
        ),
        migrations.CreateModel(
            name='SiteCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('homepage_heading', models.CharField(blank=True, help_text='A hero heading to appear on the homepage', max_length=128)),
                ('short_bio', models.TextField(blank=True, help_text='A short bio to appear on the homepage')),
                ('footer_text', wagtail.fields.RichTextField(blank=True)),
                ('copyright_author', models.CharField(blank=True, max_length=64)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_m5ka_core_sitecopy'), models.UniqueConstraint(fields=('locale',), name='unique_sitecopy_per_locale')],
            },
        ),
    ]
