# Generated by Django 6.1.1 on 2026-09-10 15:49

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m5ka_core', '0002_settings'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('standout_text', 3), ('image', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'h2', 'template': 'blocks/subheading.html'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'hr', 'link']}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'template': 'blocks/standout_text.html'}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('thumb', 'Thumbnail'), ('full', 'Full')]}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('size', 6)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogRoot',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('standout_text', 3), ('image', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'h2', 'template': 'blocks/subheading.html'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'hr', 'link']}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'template': 'blocks/standout_text.html'}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('thumb', 'Thumbnail'), ('full', 'Full')]}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('size', 6)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
