# Generated by Django 6.1.1 on 2026-09-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m5ka_core', '0003_blogpost_blogroot_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='customisationsettings',
            name='homepage_heading',
            field=models.CharField(blank=True, help_text='A hero heading to appear on the homepage', max_length=128),
        ),
    ]
