# Generated by Django 6.1.1 on 2026-09-10 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m5ka_core', '0004_customisationsettings_homepage_heading'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customisationsettings',
            name='homepage_avatar',
            field=models.ForeignKey(blank=True, help_text='An avatar image to appear on the homepage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
