# Generated by Django 6.1.1 on 2026-09-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m5ka_core', '0005_navigationsettings_to_menus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationSettings',
        ),
    ]
