# Generated by Django 6.1.1 on 2026-09-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m5ka_core', '0007_alter_blogpost_body_alter_page_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialsettings',
            name='goatcounter_hostname',
        ),
    ]
