# Generated by Django 6.1.1 on 2026-09-13 10:59

import django.core.validators
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m5ka_core', '0008_remove_socialsettings_goatcounter_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('standout_text', 3), ('image', 7), ('youtube_embed', 9), ('divider', 10), ('page_link', 11), ('page_cards', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'h2', 'template': 'blocks/subheading.html'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'hr', 'link']}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'template': 'blocks/standout_text.html'}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('thumb', 'Thumbnail'), ('full', 'Full')]}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('size', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is just the part after ?v= in the URL', 'label': 'YouTube video ID', 'validators': [django.core.validators.RegexValidator('^[A-Za-z0-9_-]{11}$', 'Enter the 11-character video ID')]}), 9: ('wagtail.blocks.StructBlock', [[('youtube_video_id', 8)]], {}), 10: ('wagtail.blocks.static_block.StaticBlock', (), {'icon': 'minus', 'template': 'blocks/divider.html'}), 11: ('wagtail.blocks.PageChooserBlock', (), {'icon': 'link', 'template': 'blocks/page_link.html'}), 12: ('wagtail.blocks.PageChooserBlock', (), {}), 13: ('wagtail.blocks.ListBlock', (12,), {'icon': 'table', 'template': 'blocks/page_cards.html'})}),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('standout_text', 3), ('image', 7), ('youtube_embed', 9), ('divider', 10), ('page_link', 11), ('page_cards', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'template': 'blocks/heading.html'}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'h2', 'template': 'blocks/subheading.html'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'hr', 'link']}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'template': 'blocks/standout_text.html'}), 4: ('wagtail.images.blocks.ImageBlock', [], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('thumb', 'Thumbnail'), ('full', 'Full')]}), 7: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('size', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'This is just the part after ?v= in the URL', 'label': 'YouTube video ID', 'validators': [django.core.validators.RegexValidator('^[A-Za-z0-9_-]{11}$', 'Enter the 11-character video ID')]}), 9: ('wagtail.blocks.StructBlock', [[('youtube_video_id', 8)]], {}), 10: ('wagtail.blocks.static_block.StaticBlock', (), {'icon': 'minus', 'template': 'blocks/divider.html'}), 11: ('wagtail.blocks.PageChooserBlock', (), {'icon': 'link', 'template': 'blocks/page_link.html'}), 12: ('wagtail.blocks.PageChooserBlock', (), {}), 13: ('wagtail.blocks.ListBlock', (12,), {'icon': 'table', 'template': 'blocks/page_cards.html'})}),
        ),
    ]
